<a href="https://colab.research.google.com/github/ayushhendre/AI/blob/master/6JULY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a='ayush hendre'
k=a.split()
k

['ayush', 'hendre']

In [ ]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [ ]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(3,)

In [ ]:
a1=np.array([[1,2,3],[1,1,1]])
a1

array([[1, 2, 3],
       [1, 1, 1]])

In [ ]:
a1.shape

(2, 3)

In [ ]:
a1.shape[1]

3

In [ ]:
a1.sum(axis=1)

array([6, 3])

In [ ]:
np.random.seed(1)

In [ ]:
a2=np.random.rand(64,64,3)


In [ ]:
a2

array([[[0.68650093, 0.83462567, 0.01828828],
        [0.75014431, 0.98886109, 0.74816565],
        [0.28044399, 0.78927933, 0.10322601],
        ...,
        [0.01501898, 0.17619626, 0.33206357],
        [0.13099684, 0.80949069, 0.34473665],
        [0.94010748, 0.58201418, 0.87883198]],

       [[0.84473445, 0.90539232, 0.45988027],
        [0.54634682, 0.79860359, 0.28571885],
        [0.49025352, 0.59911031, 0.01553328],
        ...,
        [0.63378676, 0.80296324, 0.6968005 ],
        [0.76621138, 0.34245412, 0.84585148],
        [0.42876877, 0.82400987, 0.62649616]],

       [[0.14342305, 0.0783869 , 0.01833264],
        [0.066725  , 0.45858381, 0.11334192],
        [0.02778335, 0.75486148, 0.39485048],
        ...,
        [0.23170231, 0.20762566, 0.91733356],
        [0.71131452, 0.55388461, 0.30451799],
        [0.83485405, 0.43530596, 0.92345622]],

       ...,

       [[0.35099751, 0.17268062, 0.2694481 ],
        [0.10683574, 0.74668071, 0.93906463],
        [0.61926614, 0

In [ ]:
a2[:,:,2]

array([[0.01828828, 0.74816565, 0.10322601, ..., 0.33206357, 0.34473665,
        0.87883198],
       [0.45988027, 0.28571885, 0.01553328, ..., 0.6968005 , 0.84585148,
        0.62649616],
       [0.01833264, 0.11334192, 0.39485048, ..., 0.91733356, 0.30451799,
        0.92345622],
       ...,
       [0.2694481 , 0.93906463, 0.256275  , ..., 0.1884362 , 0.86101569,
        0.23522419],
       [0.81284488, 0.853745  , 0.01136668, ..., 0.10987567, 0.87297768,
        0.01090942],
       [0.24989319, 0.93919102, 0.49162229, ..., 0.34259378, 0.34272414,
        0.00119213]])

In [ ]:
c=np.array([[2,3,4,5],[7,8,9,10]])
c.shape

(2, 4)

In [ ]:
d=c.T
d.shape

(4, 2)

In [ ]:
A=np.array([[2,3],[4,5]])
B=np.array([[1,2,3],[1,1,1]])
C=np.dot(A,B)
C.shape

(2, 3)

In [ ]:
A1=np.zeros((5,1))
print(A1)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [ ]:
c1=['a1','b1','d1']
type(c1)

list

In [ ]:
c1.append('e1')
print(c1)

['a1', 'b1', 'd1', 'e1']


In [ ]:
dir(c1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
e1={'a':11,'b':12}
type(e1)
e1.values()

dict_values([11, 12])

In [ ]:
##sigmoid
x=np.array([1,2,3])
x1=1/(1+np.exp(-x))
print(x1)

[0.73105858 0.88079708 0.95257413]


In [ ]:
##derivatives of sigmoid
x1*(1-x1)

array([0.19661193, 0.10499359, 0.04517666])

In [ ]:
img=np.random.rand(2,2,3)

In [ ]:
new_img=img.reshape((img.shape[0]*img.shape[1]*img.shape[2],1))
new_img.shape

(12, 1)

In [ ]:
print(new_img)

[[0.98450583]
 [0.41181781]
 [0.69381811]
 [0.35016004]
 [0.92964561]
 [0.21774556]
 [0.3411957 ]
 [0.59046739]
 [0.22015241]
 [0.09423997]
 [0.29527353]
 [0.71582892]]


In [ ]:
new_img1=img.reshape(img.shape[0],-1).T
new_img1.shape

(6, 2)

In [ ]:
x1=np.array([[0,3,4],[2,6,4]])
x1

array([[0, 3, 4],
       [2, 6, 4]])

In [ ]:
x_norm=np.linalg.norm(x1,ord=2,axis=1,keepdims=True)
x_norm.shape
x_sd=x1/x_norm
x_sd

array([[0.        , 0.6       , 0.8       ],
       [0.26726124, 0.80178373, 0.53452248]])

In [ ]:
w,b,X,Y=np.array([[1],[2]]),2,np.array([[1,2,-1],[3,4,-3.2]]),np.array([[1,0,1]])

In [ ]:
X.shape

(2, 3)

In [ ]:
print(X)

[[ 1.   2.  -1. ]
 [ 3.   4.  -3.2]]
